---
title: "P3"
author: "Jonathan Demeter"
date: "4/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Read in data
```{r}
spotify <- read.csv("data.csv")
#spotify_by_artist <- read.csv("data_by_artist.csv")

spotify <- subset(spotify, select = -c(id, name, release_date))
spotify$artists <- as.factor(spotify$artists)
spotify$key <- as.factor(spotify$key)
str(spotify)
summary(spotify)
```

## test and train
```{r}
set.seed(1234)

test_set <- sample(1:nrow(spotify), 30000)

spotify_train <- spotify[-test_set, ]
spotify_test <- spotify[test_set, ]
```


## Linear Model
```{r}
spotify_lin <- lm(popularity ~ valence + speechiness + 
                    mode + liveness + key + instrumentalness + 
                    explicit + energy + duration_ms + danceability + acousticness, data = spotify)
summary(spotify_lin)

```
## Logistic Regressions
```{r}
library(class)
library(caret)
library(gmodels)

popularity_threshold <- 42

spotify_train$popularity_bin <-spotify_train$popularity / 100
median(spotify_train$popularity_bin)
summary(spotify_train$popularity_bin)
spotify_train$popularity_bin <- ifelse(spotify_train$popularity > popularity_threshold, 1, 0)

spotify_test$popularity_bin <- spotify_test$popularity / 100
mean(spotify_test$popularity_bin)
spotify_test$popularity_bin <- ifelse(spotify_test$popularity > popularity_threshold, 1, 0)
summary(as.factor(spotify_test$popularity_bin))
spotify_log <- glm(popularity_bin ~ valence + speechiness + 
                    liveness + instrumentalness + 
                    energy + duration_ms + danceability + acousticness,
                   data = spotify_train, family = "binomial")
summary(spotify_log)

spotify_pred <- predict(spotify_log, newdata = spotify_test, type = "response")
spotify_pred <- ifelse(spotify_pred >  popularity_threshold/100, 1, 0)
summary(spotify_pred)
CrossTable(x = spotify_pred, y = spotify_test$popularity_bin, prop.chisq=FALSE)
confusionMatrix(spotify_pred, spotify_test$popularity_bin)
```
Look at spotify dancability score
```{r}

dance_model <- lm(danceability ~ tempo + valence + speechiness + 
                    mode + liveness + key + instrumentalness + 
                    explicit + energy + duration_ms + acousticness, data = spotify)
summary(dance_model)
```

```{r}
spotify$decades <- cut(spotify$year, breaks = c(0,1929, 1939, 1949, 1959, 1969, 1979, 1989, 1999, 2009, 2019, Inf), labels = c("20s", "30s", "40s", "50s", "60s", "70s", "80s", "90s", "2000s", "2010s", "2020s"))
summary(spotify)
```

```{r}
ggplot(spotify, aes(x = decades, y = tempo, fill=decades)) + 
  geom_bar(stat = "summary", fun = "mean")
```
```{r}
ggplot(spotify, aes(x = decades, y = popularity, fill=decades)) + 
  geom_bar(stat = "summary", fun = "mean")
```
```{r}
ggplot(spotify, aes(x = decades, y = valence, fill=decades)) + 
  geom_bar(stat = "summary", fun = "mean")
```
```{r}
ggplot(spotify, aes(x = decades, y = danceability, fill=decades)) + 
  geom_bar(stat = "summary", fun = "mean")
```
```{r}
ggplot(spotify, aes(x = decades, y = loudness, fill=decades)) + 
  geom_bar(stat = "summary", fun = "mean")
```
```{r}
ggplot(spotify, aes(x = decades, y = explicit, fill=decades)) + 
  geom_bar(stat = "summary", fun = "mean")
```

```{r}
summary(spotify$decades)
```

```{r}
ggplot(spotify, aes(x = decades, y = duration_ms, fill=decades)) + 
  geom_bar(stat = "summary", fun = "mean")
```
```{r}
hist(spotify$popularity)
```

```{r}
summary(spotify)
quantile(spotify$popularity, probs=seq(.1, .9, by = .1))

spotify$hit_class <- ifelse(spotify$popularity >= 56, "mega-hit", ifelse(spotify$popularity > 42, "hit", "not hit"))
spotify$hit_class <- as.factor(spotify$hit_class)
```
```{r}
library(C50)
```

```{r "Song Popularity"}
# Superhit vs not superhit classification with log model and knn
spotify$binary_hit_class <- ifelse(spotify$hit_class == "mega-hit", 1, 0)
spotify$binary_hit_class <- as.factor(spotify$binary_hit_class)
log_train <- spotify[-test_set,]
log_test <- spotify[test_set,]
log_test_labels <- log_test$binary_hit_class
log_test <- subset(log_test, select=-c(binary_hit_class))
log_train <- subset(log_train, select=-c(artists, popularity, year, hit_class))
log_model <- train(binary_hit_class ~ ., data = log_train, method = "glm", family="binomial")
summary(log_model)
```

```{r}
pred <- predict(log_model, log_test)
```


```{r}
confusionMatrix(pred, log_test_labels)
```
```{r knn for popularity}
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

#Applying normalization function to all columns except the response variable
knn_train <- subset(log_train, select=-c(decades))
knn_test <- subset(log_test, select=-c(artists, popularity, year, decades, hit_class))
knn_train <- as.data.frame(lapply(knn_train[1:(ncol(knn_train)-1)], normalize))
knn_test <- as.data.frame(lapply(knn_test[1:ncol(knn_test)], normalize))
```

```{r}
#sqrt nrows = 379
knn_model_pred <- knn(train=knn_train, test=knn_test, cl=log_train$binary_hit_class, k=379)
```

```{r}
confusionMatrix(knn_model_pred, log_test_labels)
```

